theme: jekyll-theme-cayman
title: [The Mortality Surveillance & Reporting Laboratory at Boston University]
description: [This website features tools for identifying patterns of county mortality throughout the United States and potential underreported COVID-19 deaths]
author: Stokes team
