theme: jekyll-theme-cayman
title: [The Mortality Surveillance & Reporting Laboratory at Boston University]
description: [Our team is dedicated to investigating and evaluating discrepencies in Covid-19 mortality throughout the US]
author: Stokes team
